name: Build and Publish Docker Image
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push consumer
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./dev-ops/docker-consumer/Dockerfile
          build-args: |
            AWS_REGION=${{ vars.AWS_REGION }}
            AWS_SQS_URL=${{ vars.AWS_SQS_URL }}
            AWS_SQS_NAME=${{ vars.AWS_SQS_NAME }}
          tags: |
            yzhbankov/aws-sqs-consumer:${{ steps.set_version.outputs.no-dash }}
            yzhbankov/aws-sqs-consumer:latest

      - name: Build and push producer
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./dev-ops/docker-producer/Dockerfile
          build-args: |
            AWS_REGION=${{ vars.AWS_REGION }}
            AWS_SQS_URL=${{ vars.AWS_SQS_URL }}
            AWS_SQS_NAME=${{ vars.AWS_SQS_NAME }}
          tags: |
            yzhbankov/aws-sqs-producer:${{ steps.set_version.outputs.no-dash }}
            yzhbankov/aws-sqs-producer:latest
